// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niqrdozrxkiuxrdxktws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pcXJkb3pyeGtpdXhyZHhrdHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzczOTEsImV4cCI6MjA2NDkxMzM5MX0.iX68P3ei6mw35cf3YTny5qGpil6O7m2dXB_Y-A7JWYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);